version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: user_management
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: secretpassword
      DB_NAME: user_management

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mysql-data:
